export const MENU_ITEM_LIST_REQUEST = 'MENU_ITEM_LIST_REQUEST';
export const MENU_ITEM_LIST_SUCCESS = 'MENU_ITEM_LIST_SUCCESS';
export const MENU_ITEM_LIST_FAIL = 'MENU_ITEM_LIST_FAIL';

export const MENU_ITEM_DETAILS_REQUEST = 'MENU_ITEM_DETAILS_REQUEST';
export const MENU_ITEM_DETAILS_SUCCESS = 'MENU_ITEM_DETAILS_SUCCESS';
export const MENU_ITEM_DETAILS_FAIL = 'MENU_ITEM_DETAILS_FAIL';

export const MENU_ITEM_CREATE_REQUEST = 'MENU_ITEM_CREATE_REQUEST';
export const MENU_ITEM_CREATE_SUCCESS = 'MENU_ITEM_CREATE_SUCCESS';
export const MENU_ITEM_CREATE_FAIL = 'MENU_ITEM_CREATE_FAIL';
export const MENU_ITEM_CREATE_RESET = 'MENU_ITEM_CREATE_RESET';

export const MENU_ITEM_UPDATE_REQUEST = 'MENU_ITEM_UPDATE_REQUEST';
export const MENU_ITEM_UPDATE_SUCCESS = 'MENU_ITEM_UPDATE_SUCCESS';
export const MENU_ITEM_UPDATE_FAIL = 'MENU_ITEM_UPDATE_FAIL';
export const MENU_ITEM_UPDATE_RESET = 'MENU_ITEM_UPDATE_RESET';

export const MENU_ITEM_DELETE_REQUEST = 'MENU_ITEM_DELETE_REQUEST';
export const MENU_ITEM_DELETE_SUCCESS = 'MENU_ITEM_DELETE_SUCCESS';
export const MENU_ITEM_DELETE_FAIL = 'MENU_ITEM_DELETE_FAIL';
